### ISSUE TITLE
Can't access Watcher via FQDN?

### ISSUE THREAD

**Issue by xme** [Felix83000/Watcher#12]
**Describe the bug**
Added the server IP in allowed_host as expected.
But I can't access via FQDN?
=> Bad request

**Comment by Felix83000** [comment]
Can you show your .env file please?

**Comment by Felix83000** [comment]
Please look this issue: #8

**Comment by Felix83000** [comment]
After changing the file you need to do this:

> - `docker-compose down`
> 
> - `docker-compose up`

**Comment by xme** [comment]
`# Time Zone
TZ=Europe/Brussels

# SECURITY WARNING: In production please put DJANGO_DEBUG environment variable to False
DJANGO_DEBUG=False

# SECURITY WARNING: keep the secret key used in production secret!
# use 'openssl rand -base64 33' to generate
DJANGO_SECRET_KEY=xxxxxxxxxxx

# In case of "Bad Request" Error when accessing Watcher web interface.
# Fill this variable with your Watcher Server Instance IP.
# It is limited to a single IP address. Please use this syntax: ALLOWED_HOST=X.X.X.X
ALLOWED_HOST=192.168.240.10

# DJANGO EMAIL CONFIGURATION
EMAIL_FROM=xxxxx
SMTP_SERVER=xxxxxxx
WATCHER_URL=https://xxxxxx

# THE HIVE SETUP
THE_HIVE_URL=https://xxxxxxx
THE_HIVE_KEY=xxxxxxxx
THE_HIVE_CASE_ASSIGNEE=xavier

# MISP Setup
MISP_URL=https://xxxxxxxx
MISP_VERIFY_SSL=False
MISP_KEY=xxxxxxxxx
# Optional
MISP_TICKETING_URL=

# LDAP Setup
AUTH_LDAP_SERVER_URI=
AUTH_LDAP_BIND_DN=
AUTH_LDAP_BIND_PASSWORD=
AUTH_LDAP_BASE_DN=
AUTH_LDAP_FILTER=(uid=%(user)s)

# Searx Setup
SEARX_HOSTNAME=10.10.10.3:8080
SEARX_PROTOCOL=http://

# automaticaly update settings to the new version
# comment this line if you made / will make some modifications to the settings
SEARX_COMMAND=-f

# If you have a proxy, please fill these variables
HTTP_PROXY=
HTTPS_PROXY=`

**Comment by Felix83000** [comment]
The configuration seems okay... 

Please do this:

- Set `DJANGO_DEBUG` to `True`

- `docker-compose down`

- `docker-compose up`

- Try to access Watcher via FQDN and upload a screenshot here.

Thx

**Comment by xme** [comment]
<img width="2018" alt="Screenshot 2020-10-23 at 10 38 12" src="https://user-images.githubusercontent.com/480944/96976464-2c36f980-151c-11eb-9ca0-0b9d8587c305.png">

**Comment by Felix83000** [comment]
Okay, so as you can see `ALLOWED_HOST` variable is set to `192.168.240.10`.

So you need to add the IP value that you have hidden "You may need to add **X.X.X.X** to ALLOWED_HOST"

**Comment by xme** [comment]
But the hidden value is my FQDN... That's why I don't understand ;-) 
Sorry, I had to mention this immediately

**Comment by Felix83000** [comment]
The condition to be satisfied is that the host header (or X-Forwarded-Host if USE_X_FORWARDED_HOST is enabled) should match one of the values in ALLOWED_HOSTS.

**Comment by Felix83000** [comment]
Try to put your FQDN instead.

**Comment by Felix83000** [comment]
Or you can do this: `ALLOWED_HOST=*` but it is less secure...

**Comment by xme** [comment]
It worked with the FQDN set as allowed_host! 
Nope, no "*" ;-)
Tx!

**Comment by Felix83000** [comment]
I updated the documentation related to this issue: https://github.com/Felix83000/Watcher/commit/42a632ed0916035c6e7d2cfcd94935e7aa508e97
