### ISSUE TITLE
Tweets not found

### ISSUE THREAD

**Issue by jer-em** [Felix83000/Watcher#13]
**Describe the bug**
The Twitter search engine request is in error. Unable to display results in Watcher.

**To Reproduce**
1. Go to '0.0.0.0:9002'
2. Click on a 'Trendy Word'
3. Scroll down to 'Tweet(s) related to ***'
4. See the problem
5. Check the problem when starting the service on the line "searx-checker | twitter....ERROR No result"

**Screenshots**
![twitter_error](https://user-images.githubusercontent.com/61385457/97099309-f1ea6b00-1687-11eb-8262-86131f50e2f9.png)

**Comment by Felix83000** [comment]
Hello,

I think that your navigator is blocking external Twitter access from Watcher.

Are you using "disconnect" extension or another "tracker" navigator extension?
If it is the case, please add Watcher to the allow list. 

Regards,

**Comment by lbrossault** [comment]
Hello,

I have the same issue.
From watcher docker instance, when I launch:
`wget http://10.10.10.7/?action=display&bridge=Twitter&context=By+username&u=CSAsingapore&norep=on&nopic=on&noimg=on&noimgscaling=on&format=Mrss`

I receive **400 Bad Request** answer.

**Comment by Felix83000** [comment]
Hello,

Are you using Watcher through a Proxy?
If yes, you need to add 10.10.10.7 in your no proxy env variable. 

Regards

**Comment by lbrossault** [comment]
Hello,

It's better, thanks.

From homepage, I can see twitter in "Article(s) related to" table, but cannot see "Tweet(s) related to" tweet messages.
Any idea ?


Regards,

**Comment by Felix83000** [comment]
> Hello,
> 
> It's better, thanks.
> 
> From homepage, I can see twitter in "Article(s) related to" table, but cannot see "Tweet(s) related to" tweet messages.
> Any idea ?
> 
> 
> Regards,

It can be an extension on your navigator, add blocker or something else

**Comment by lbrossault** [comment]
It works fine now. Sorry for the stupid question !

Regards,
