### ISSUE TITLE
[Feature Request] Bulk registration of new RSS feeds (or any other data)

### ISSUE THREAD

**Issue by xme** [Felix83000/Watcher#15]
**Is your feature request related to a problem? Please describe.**
I have a bunch of RSS feeds to add to my current Watcher instance and adding them one by one is sloooooow.

**Describe the solution you'd like**
A way to upload a text file with RSS feeds? (with a validation process - correct XML returned etc)
Or fetch data from a URL

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Felix83000** [comment]
Hello,

We implemented this functionality in the last commit b7cdf1e56091cfa0db47f253260f40ac94f27c7c.

May you test it and give your feedback?
