### ISSUE TITLE
[Feature Request] Report alerts in Twisted DNS directly to TheHive or MISP

### ISSUE THREAD

**Issue by cudeso** [Felix83000/Watcher#16]
**Describe the solution you'd like**
Apart from the "Monitor abc" (twisted domain) button, it would be interesting to have the option to directly send the domain to TheHive (or MISP).

**Comment by Felix83000** [comment]
Hello,

May you test the new feature and give your feedback?

Thx

**Comment by cudeso** [comment]
Hi @Felix83000 . Thank you for the effort! I'll have a look at the new features next week and provide you feedback!

**Comment by Felix83000** [comment]
I assumed it works as expected.
I closed this issue. Do not hesitate to reopen in case of problem.
