### ISSUE TITLE
Documentation website monitoring RTIR?

### ISSUE THREAD

**Issue by 8ear** [Felix83000/Watcher#22]
Hi,
At website monitoring, what is the RTIR?
Which sites should be added our own sites or suspicious sites?

**Comment by Felix83000** [comment]
Hi,
RTIR is basically a ticket ID, it will be linked to your website, and specified it in email notifications. You can use it to feed your ticketing system by adding it in subscribers.

You can monitor any website you want. But the purpose of this module is to monitor the administration of attackers.

**Comment by 8ear** [comment]
Thanks.
