### ISSUE TITLE
Questions about watcher

### ISSUE THREAD

**Issue by s2367513** [Felix83000/Watcher#23]
I have some questions
On the homepage, how should I set it to be the same as on your picture
thanks

![image](https://user-images.githubusercontent.com/50659945/103135032-6c6b5180-46f0-11eb-95f7-1ea04fb6db00.png)

**Comment by Felix83000** [comment]
Hi,

You just need to wait for Watcher to crawl the data.
It will happen every 30 minutes.

Regards,

**Comment by Felix83000** [comment]
Just be sure that you added the default RSS feeds : https://felix83000.github.io/Watcher/README.html#populate-your-database

You can also personalize the RSS feeds by adding your own : https://felix83000.github.io/Watcher/README.html#add-your-rss-source-to-threats-detection

**Comment by s2367513** [comment]
Thanks, i will try again

**Comment by raghuisin** [comment]
waited for 6 hrs no luck still don't see trendy words 
<img width="1599" alt="Screen Shot 2021-04-03 at 2 56 20 AM" src="https://user-images.githubusercontent.com/32757324/113471122-40b2e280-9428-11eb-8ced-073d860177bb.png">

**Comment by Felix83000** [comment]
> waited for 6 hrs no luck still don't see trendy words 
> <img width="1599" alt="Screen Shot 2021-04-03 at 2 56 20 AM" src="https://user-images.githubusercontent.com/32757324/113471122-40b2e280-9428-11eb-8ced-073d860177bb.png">
> 

Did you added the default RSS feeds? https://felix83000.github.io/Watcher/README.html#populate-your-database

Please also check your connection from your server.

**Comment by raghuisin** [comment]
RSS feeds and blocklist are added.  I checked the connection from watcher. 
<img width="1753" alt="Screen Shot 2021-04-03 at 11 46 49 AM" src="https://user-images.githubusercontent.com/32757324/113483655-8f856a00-9472-11eb-8ac7-137062d847f4.png">

**Comment by raghuisin** [comment]
anyway to check the logs ?

**Comment by Felix83000** [comment]
It is strange.
You can check the logs with the `docker-compose up` command.

**Comment by raghuisin** [comment]
Creating network "watcher_default" with the default driver
Creating rss-bridge    ... done
Creating searx         ... done
Creating db_watcher    ... done
Creating searx-checker ... done
Creating watcher       ... done
Attaching to rss-bridge, searx, db_watcher, watcher, searx-checker
rss-bridge       | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.10.10.7. Set the 'ServerName' directive globally to suppress this message
rss-bridge       | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.10.10.7. Set the 'ServerName' directive globally to suppress this message
rss-bridge       | [Sat Apr 03 18:13:35.567387 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.16 configured -- resuming normal operations
rss-bridge       | [Sat Apr 03 18:13:35.567482 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
db_watcher       | 2021-04-03 18:13:37+02:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.23-1debian10 started.
searx            | searx version 1.0.0-1.0.0
searx            |
searx            | Use existing /etc/searx/uwsgi.ini
searx            | Use existing /etc/searx/settings.yml
searx            | Listen on 10.10.10.3:8080
searx            | [uWSGI] getting INI configuration from /etc/searx/uwsgi.ini
searx            | [uwsgi-static] added mapping for /static => /usr/local/searx/searx/static
db_watcher       | 2021-04-03 18:13:37+02:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db_watcher       | 2021-04-03 18:13:37+02:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.23-1debian10 started.
db_watcher       | 2021-04-03T16:13:38.073063Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.23) starting as process 1
db_watcher       | 2021-04-03T16:13:38.081371Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
db_watcher       | 2021-04-03T16:13:38.282725Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
searx-checker    | Sleep 116 seconds
db_watcher       | 2021-04-03T16:13:38.514089Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
db_watcher       | 2021-04-03T16:13:38.595125Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
db_watcher       | 2021-04-03T16:13:38.595513Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
db_watcher       | 2021-04-03T16:13:38.602932Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db_watcher       | 2021-04-03T16:13:38.627028Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.23'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
watcher          | db_watcher is up, starting Watcher.
watcher          | Performing system checks...
watcher          |
watcher          | System check identified no issues (0 silenced).
watcher          | April 03, 2021 - 18:13:41
watcher          | Django version 3.1.6, using settings 'watcher.settings'
watcher          | Starting development server at http://0.0.0.0:9002/
watcher          | Quit the server with CONTROL-C.

**Comment by Felix83000** [comment]
Everything seems ok.

Don't forget to run Watcher in background using this command: `docker-compose up -d` 

If you already did this, please try to upgrade all Docker images using this process: https://thalesgroup-cert.github.io/Watcher/README.html#update-watcher

Regards

**Comment by raghuisin** [comment]
thanks for the response. No luck.:-(

**Comment by raghuisin** [comment]
finally , it started working after 24-48 hrs. Thanks for you support.

**Comment by Felix83000** [comment]
Great! We will see how to improve the first Watcher startup.
