### ISSUE TITLE
Trendy words and "word cloud" not updating

### ISSUE THREAD

**Issue by dagobertdebug** [Felix83000/Watcher#27]
Hi

First of all, thanks for this great tool! 

I initially installed Watcher on 11 January, since then the "trendy words" and "word cloud" is not updating, no new words are showing up.

![image](https://user-images.githubusercontent.com/30775398/104890811-5c9e0080-5970-11eb-89c9-a201f645c934.png)

Any idea what is wrong, or how to trigger a manual update.

Cheers,
Dago

**Comment by dagobertdebug** [comment]
I removed all of my own sources and now it is updating again, so the problem could be within the sources (e.g. if the url is not vaild).

**Comment by Felix83000** [comment]
Hi,

Did you make sure that all your sources was URLs leading to an RSS file (Atom 1.0, Atom 0.3, RSS 2.0, RSS 2.0 with Namespaces, RSS 1.0)?

(Cf. https://felix83000.github.io/Watcher/README.html#add-your-rss-source-to-threats-detection)

Regards,

**Comment by dagobertdebug** [comment]
For testing I removed all sources and run the script for default sources. Lets see.

**Comment by Felix83000** [comment]
Yes keep me in touch.

The logs are displayed when you do `docker-compose up`

**Comment by Felix83000** [comment]
The crawling script runs every 30 minutes. If there is an error you will see it.

**Comment by Felix83000** [comment]
Also, make sure that you have the latest `rssbridge/rss-bridge` docker's image: https://felix83000.github.io/Watcher/README.html#update-watcher

**Comment by dagobertdebug** [comment]
Thanks for your tips! 

I started to add my sources yesterday step by step and it seems to work until know.

Will do the update now.

**Comment by dagobertdebug** [comment]
Hi, here are some logs with errors I see with my instance:

 Job "main_watch (trigger: cron[day_of_week='mon-fri', hour='7-18', minute='*/30'], next run at: 2021-01-20 14:00:00 CET)" raised an exception
watcher          | Traceback (most recent call last):
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
watcher          |     return self.cursor.execute(sql, params)
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
watcher          |     return self.cursor.execute(query, args)
watcher          |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
watcher          |     res = self._query(query)
watcher          |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
watcher          |     db.query(q)
watcher          |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
watcher          |     _mysql.connection.query(self, query)
watcher          | MySQLdb._exceptions.DataError: (1406, "Data too long for column 'url' at row 1")
watcher          |
watcher          | The above exception was the direct cause of the following exception:
watcher          |
watcher          | Traceback (most recent call last):
watcher          |   File "/usr/local/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
watcher          |     retval = job.func(*job.args, **job.kwargs)
watcher          |   File "/app/Watcher/threats_watcher/core.py", line 79, in main_watch
watcher          |     focus_on_top(settings.WORDS_OCCURRENCE)
watcher          |   File "/app/Watcher/threats_watcher/core.py", line 234, in focus_on_top
watcher          |     PostUrl.objects.create(url=posturl, created_at=date)
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
watcher          |     return getattr(self.get_queryset(), name)(*args, **kwargs)
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
watcher          |     obj.save(force_insert=True, using=self.db)
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 753, in save
watcher          |     self.save_base(using=using, force_insert=force_insert,
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 790, in save_base
watcher          |     updated = self._save_table(
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 895, in _save_table
watcher          |     results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 933, in _do_insert
watcher          |     return manager._insert(
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
watcher          |     return getattr(self.get_queryset(), name)(*args, **kwargs)
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1254, in _insert
watcher          |     return query.get_compiler(using=using).execute_sql(returning_fields)
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
watcher          |     cursor.execute(sql, params)
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
watcher          |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
watcher          |     return executor(sql, params, many, context)
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
watcher          |     return self.cursor.execute(sql, params)
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
watcher          |     raise dj_exc_value.with_traceback(traceback) from exc_value
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
watcher          |     return self.cursor.execute(sql, params)
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
watcher          |     return self.cursor.execute(query, args)
watcher          |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
watcher          |     res = self._query(query)
watcher          |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
watcher          |     db.query(q)
watcher          |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
watcher          |     _mysql.connection.query(self, query)
watcher          | django.db.utils.DataError: (1406, "Data too long for column 'url' at row 1")

**Comment by dagobertdebug** [comment]
searx-checker    | deviantart.Traceback (most recent call last):
searx-checker    |   File "./checker/checker.py", line 228, in <module>
searx-checker    |     main(args.url, args.o)
searx-checker    |   File "./checker/checker.py", line 215, in main
searx-checker    |     state = check_engines_state(instance_url, engines)
searx-checker    |   File "./checker/checker.py", line 168, in check_engines_state
searx-checker    |     provides_results = _request_results(instance_url, engine)
searx-checker    |   File "./checker/checker.py", line 156, in _request_results
searx-checker    |     engine_result = _query_engine_result(instance_url, engine, query)
searx-checker    |   File "./checker/checker.py", line 146, in _query_engine_result
searx-checker    |     return _check_response(resp)
searx-checker    |   File "./checker/checker.py", line 132, in _check_response
searx-checker    |     return _check_results(resp_json['results'])
searx-checker    |   File "./checker/checker.py", line 86, in _check_results
searx-checker    |     if not _check_result(result):
searx-checker    |   File "./checker/checker.py", line 78, in _check_result
searx-checker    |     return _is_url_image(result.get('thumbnail_src'))
searx-checker    |   File "./checker/checker.py", line 42, in _is_url_image
searx-checker    |     if image_url.startswith('//'):
searx-checker    | AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by Felix83000** [comment]
Ok so I think one of your urls is larger than the "max_length" (250 characters).

Can you confirm that this is the case and, if so, the number of characters of the largest url?

I will make the change if needed.

**Comment by dagobertdebug** [comment]
no sorry, the sources I have added are not exceeding 250 chars....

**Comment by Felix83000** [comment]
Okay I see, It is an article link which exceed 250chars... I will increase this value in order to handle this issue.

Thanks for reporting.

Regards,

**Comment by dagobertdebug** [comment]
Alright, glad that you figured out.

Regarding the word cloud and trendy words: yesterday I have removed all my sources related to twitter, and today it seems that the content is updating, so maybe I have done something wrong with that twitter sources. here are few of those I wanted to add, maybe you see something wrong with it:

http://10.10.10.7/?action=display&bridge=Twitter&context=By+username&u=cryptolaemus1&norep=on&nopic=on&noimg=on&noimgscaling=on&format=Mrss

http://10.10.10.7/?action=display&bridge=Twitter&context=By+username&u=threatmeter&norep=on&nopic=on&noimg=on&noimgscaling=on&format=Mrss

http://10.10.10.7/?action=display&bridge=Twitter&context=By+username&u=VulmonFeeds&norep=on&nopic=on&noimg=on&noimgscaling=on&format=Mrss

**Comment by Felix83000** [comment]
I checked on a public instance and it looks correct:

https://wtf.roflcopter.fr/rss-bridge/?action=display&bridge=Twitter&context=By+username&u=cryptolaemus1&norep=on&nopic=on&noimg=on&noimgscaling=on&format=Mrss
https://wtf.roflcopter.fr/rss-bridge/?action=display&bridge=Twitter&context=By+username&u=threatmeter&norep=on&nopic=on&noimg=on&noimgscaling=on&format=Mrss
https://wtf.roflcopter.fr/rss-bridge/?action=display&bridge=Twitter&context=By+username&u=VulmonFeeds&norep=on&nopic=on&noimg=on&noimgscaling=on&format=Mrss

**Comment by dagobertdebug** [comment]
Thanks. I am going to re-add those sources above and will check if the word cloud / trendy words are updating.
