### ISSUE TITLE
Watcher frontend doesn't load

### ISSUE THREAD

**Issue by hefesita** [Felix83000/Watcher#28]
**Describe the bug**
I made a clean install, enabled the default RSS but the frontend doesn't load. In console I have:
SyntaxError: invalid for/in left-hand side
The administration interface works. 
Am I doing something wrong?

**To Reproduce**
Fresh installation, just followed the steps.

**Desktop (please complete the following information):**
 - OS: CentOS 7
 - Browser Firefox

**Comment by Felix83000** [comment]
Hi,

I did a new fresh install with CentOs 7 and everything is working fine.

- Did you tried with Chrome Browser?

**Comment by hefesita** [comment]
tried Chrome and it worked
