### ISSUE TITLE
400 Bad request

### ISSUE THREAD

**Issue by Malekingc** [Felix83000/Watcher#29]
Hi everyone.

I'm still new to using Docker and it's required to install Watcher. I installed both docker and docker-compose following the guide provided here https://felix83000.github.io/Watcher/README.html.
Watcher is also installed following the same guide but once I reach this point "Try Access Watcher on http://0.0.0.0:9002 or http://yourserverip:9002." I get the "**400 Bad Request**" error.
I can see the error message on the shell of watcher VM also:
"GET / HTTP/1.1" 400 143
"GET /favicon.ico HTTP/1.1" 400 143

Am I missing something?

Thank in advance.

**Comment by Felix83000** [comment]
Hello,

Have you tried to access Watcher from your local host? (http://0.0.0.0:9002)

To access your server instance from another computer please add the server IP or FQDN in the .env file (describe [here](https://felix83000.github.io/Watcher/README.html#access-watcher-remotely-within-your-server-instance)).

Tell me if it worked. 😉

**Comment by Malekingc** [comment]
> Hello,
> 
> Have you tried to access Watcher from your local host? (http://0.0.0.0:9002)
> 
> To access your server instance from another computer please add the server IP or FQDN in the `.env` file (describe [here](https://felix83000.github.io/Watcher/README.html#access-watcher-remotely-within-your-server-instance)).
> 
> Tell me if it worked.

Oh, my bad!

I am sorry sir. I didn't finish reading the whole guide and came here to ask directly. So sorry.
Yes, it works like a charm.
I really appreciate your feedback. Thank you so much.

Have a nice day.
